name: pybind11-ke
channels:
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main
  - https://mirrors.bfsu.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1t=h7f8727e_0
  - pip=23.0.1=py310h06a4308_0
  - python=3.10.11=h7a1cb2a_2
  - readline=8.2=h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2023c=h04d1e81_0
  - wheel=0.38.4=py310h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - build==0.10.0
    - cmake==3.26.3
    - filelock==3.12.0
    - jinja2==3.1.2
    - joblib==1.2.0
    - lit==16.0.3
    - markupsafe==2.1.2
    - mpmath==1.3.0
    - networkx==3.1
    - numpy==1.24.3
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - packaging==23.1
    - pybind11-openke==0.0.1
    - pyproject-hooks==1.0.0
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - setuptools==67.7.2
    - sympy==1.12
    - threadpoolctl==3.1.0
    - tomli==2.0.1
    - torch==2.0.1
    - tqdm==4.65.0
    - triton==2.0.0
    - typing-extensions==4.5.0
prefix: /home/luyanfeng/miniconda3/envs/pybind11-ke
